Repository DCNJ-Uket/Uket-FE-v2, pull requests merged in 2025-08, with the labels that each got.

#80 style, fix: 스타일 수정 및 입장그룹 에러 수정
  apps/admin/app/(main)/entrance-manage/_components/entrance-table-section.tsx
  apps/admin/app/(main)/entrance-manage/_components/refetch-aside.tsx
  apps/admin/app/(main)/entrance-manage/page.tsx
  apps/admin/app/(main)/event-manage/_components/step-basic/entry-group-field.tsx
Labels: fix, style

#83 fix/UKET-258: 공연 등록 및 수정 에디터에서 발생하는 문제 해결
  apps/admin/app/(main)/event-manage/_components/editor/event-editor.tsx
Labels: fix

#84 fix/UKET-232: 행사(공연)일시 입력 필드 백스페이스 오류
  .github/workflows/auto-git-push-coggiee.yml
  .github/workflows/sync-repository-for-admin-service.yml
  apps/admin/app/(main)/event-manage/_components/step-basic/event-calendar-field.tsx
Labels: fix

#85 feat/UKET-213: 행사 등록 및 수정 폼에서 다음으로 버튼 수정
  apps/admin/app/(main)/event-manage/_components/step-basic/event-calendar-field.tsx
  apps/admin/app/(main)/event-manage/_components/step-basic/zipcode-field.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-basic-info.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-controller.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-event-info.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-payment-info.tsx
  apps/admin/hooks/use-add-event-form.ts
Labels: feat
