Repository DCNJ-Uket/Uket-FE-v2, pull requests merged in 2025-04, with the labels that each got.

#23 fix: 어드민 예매내역관리 api 통합
  apps/admin/app/(main)/booking-manage/_components/booking-manage-section.tsx
  apps/admin/hooks/use-ticket-book-params.ts
  packages/api/src/queries/admin-ticket.ts
  packages/api/src/types/admin-ticket.ts
Labels: fix

#27 feat: SEO 최적화
  apps/web/app/layout.tsx
  apps/web/app/robots.ts
  apps/web/app/sitemap.ts
  apps/web/config/google-analytics.tsx
  apps/web/config/site.ts
Labels: feat

#30 refactor/UKET-77: API Base Url 및 사이트 주소 변경
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  apps/web/app/(non-auth)/home/[event]/[id]/page.tsx
  apps/web/config/site.ts
  apps/web/next.config.js
  packages/api/src/admin-instance.ts
  packages/api/src/constants/auth-url.ts
  packages/api/src/instance.ts
Labels: refactor

#31 feat/UKET-78: 어드민 권한 관련 API 연결
  apps/admin/app/(main)/(super-admin)/super-admin/user-manage/_components/selector-organization.tsx
  apps/admin/app/(main)/(super-admin)/super-admin/user-manage/_components/user-add-button.tsx
  apps/admin/app/(main)/(super-admin)/super-admin/user-manage/_components/user-data-table.tsx
  apps/admin/app/(main)/(super-admin)/super-admin/user-manage/_components/user-remove-button.tsx
  apps/admin/app/(main)/(super-admin)/super-admin/user-manage/_components/user-table-section.tsx
  apps/admin/app/(main)/(super-admin)/super-admin/user-manage/page.tsx
  apps/admin/app/api/admin/users/route.ts
  apps/admin/components/footer.tsx
  apps/admin/constants/link.ts
  apps/admin/hooks/use-new-admin-form.ts
  packages/api/src/admin-instance.ts
  packages/api/src/error/handler.ts
  packages/api/src/mutations/use-mutation-manage-admin.ts
  packages/api/src/queries/admin-user.ts
  packages/api/src/types/admin-user.ts
  packages/util/src/path.ts
Labels: feat

#32 feat/UKET-84: 어드민 삭제 기능 수정
  apps/admin/app/(main)/(super-admin)/super-admin/user-manage/_components/user-remove-button.tsx
  apps/admin/app/(main)/(super-admin)/super-admin/user-manage/_components/user-table-section.tsx
  apps/admin/hooks/use-login-form.ts
  packages/api/src/types/admin-auth.ts
  packages/util/src/cookie-server.ts
Labels: feat

#34 style/UKET-89: 사업자 정보 노출을 위한 Footer 추가
  apps/web/app/page.tsx
  apps/web/components/footer.tsx
Labels: style

#35 style/UKET-69: 행사 등록 페이지 레이아웃 작업
  apps/admin/app/(main)/event-manage/_components/editor/event-editor.tsx
  apps/admin/app/(main)/event-manage/_components/editor/extensions.ts
  apps/admin/app/(main)/event-manage/_components/editor/slash-command.tsx
  apps/admin/app/(main)/event-manage/_components/event-add-section.tsx
  apps/admin/app/(main)/event-manage/_components/event-list-section.tsx
  apps/admin/app/(main)/event-manage/_components/image-uploader.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-account-info.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-basic-info.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-event-info.tsx
  apps/admin/app/(main)/event-manage/add/page.tsx
  apps/admin/app/(main)/event-manage/page.tsx
  apps/admin/components/non-available-section.tsx
  apps/admin/constants/link.ts
  apps/admin/package.json
  apps/admin/public/account-link-1.png
  apps/admin/public/account-link-2.png
  apps/admin/public/account-link-3.png
  packages/api/src/error/types.ts
  packages/ui/package.json
  packages/ui/src/components/ui/calendar.tsx
  packages/ui/src/components/ui/icon.tsx
  packages/ui/src/components/ui/popover.tsx
  packages/ui/src/components/ui/tooltip.tsx
  packages/ui/src/hooks/use-file-upload.ts
  packages/ui/src/prosemirror.css
  packages/ui/tailwind.config.ts
  packages/util/src/time.ts
  pnpm-lock.yaml
Labels: style

#37 style/UKET-95: 커스텀 캘린더 스타일 적용
  apps/admin/app/(main)/event-manage/_components/event-calendar.tsx
  apps/admin/app/(main)/event-manage/_components/step-tooltip.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-account-info.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-basic-info.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-event-info.tsx
  apps/admin/app/(main)/event-manage/_components/ticket-calendar.tsx
  apps/admin/hooks/use-event-date.ts
  apps/admin/hooks/use-ticket-date.ts
  packages/ui/package.json
  packages/ui/src/components/ui/calendar.tsx
  packages/ui/src/components/ui/icon.tsx
  packages/ui/src/components/ui/scroll-area.tsx
  pnpm-lock.yaml
Labels: feat, style

#36 feat/UKET-96: 유저 티켓 예매 지인 기능 추가
  apps/web/app/(auth)/buy-ticket/_components/step/step-date.tsx
  apps/web/app/(auth)/buy-ticket/_components/step/step-survey.tsx
  apps/web/app/(auth)/buy-ticket/_components/step/step-time.tsx
  apps/web/app/(auth)/buy-ticket/_components/survey/performer-sheet.tsx
  apps/web/app/(auth)/buy-ticket/_components/survey/question-section.tsx
  apps/web/app/(auth)/buy-ticket/buy-ticket-section.tsx
  apps/web/hooks/use-survey-form.ts
Labels: feat

#38 feat/UKET-103: 어드민 본인 정보 상세 조회 API 연결 및 그에 따른 부수 작업
  apps/admin/app/(main)/(super-admin)/super-admin/user-manage/_components/user-remove-button.tsx
  apps/admin/app/(main)/(super-admin)/super-admin/user-manage/_components/user-table-section.tsx
  apps/admin/components/greeting-header.tsx
  packages/api/src/admin-instance.ts
  packages/api/src/queries/admin-user.ts
  packages/api/src/types/admin-auth.ts
  packages/util/src/path.ts
Labels: feat, fix, refactor

#39 feat/UKET-101: 어드민 전체행사관리 api 연결
  apps/admin/app/(main)/(super-admin)/super-admin/event-manage/_components/event-table-section.tsx
  apps/admin/components/status-selector.tsx
  packages/api/src/mutations/use-mutation-change-event-status.ts
  packages/api/src/queries/admin-event-info.ts
  packages/api/src/types/admin-event.ts
Labels: feat
