Repository DCNJ-Uket/Uket-FE-v2, pull requests merged in 2025-05, with the labels that each got.

#41 feat/UKET-115: 어드민 예매내역관리 CSV 다운로드 기능
  apps/admin/app/(main)/booking-manage/_components/booking-manage-section.tsx
  apps/admin/app/(main)/booking-manage/_components/download-csv.tsx
  apps/admin/app/(main)/booking-manage/page.tsx
  apps/admin/components/admin-filter-event-list.tsx
  packages/api/src/queries/admin-ticket.ts
Labels: feat

#43 fix/UKET-130: 어드민 초대메일을 통한 회원가입 에러 픽스
  packages/util/src/path.ts
Labels: fix

#45 fix/UKET-143: 서비스 팔로업
  apps/admin/app/(main)/booking-manage/_components/download-csv.tsx
  apps/web/app/(auth)/buy-ticket/_components/step/step-complete.tsx
  apps/web/app/(auth)/my-info/_components/help-report.tsx
Labels: fix

#44 feat/UKET-70: 행사 등록 API 기능 연결
  apps/admin/app/(main)/event-manage/_components/editor/event-editor.tsx
  apps/admin/app/(main)/event-manage/_components/editor/extensions.ts
  apps/admin/app/(main)/event-manage/_components/editor/slash-command.tsx
  apps/admin/app/(main)/event-manage/_components/event-add-section.tsx
  apps/admin/app/(main)/event-manage/_components/event-calendar.tsx
  apps/admin/app/(main)/event-manage/_components/image-uploader.tsx
  apps/admin/app/(main)/event-manage/_components/step-basic/entry-group-field.tsx
  apps/admin/app/(main)/event-manage/_components/step-basic/event-calendar-field.tsx
  apps/admin/app/(main)/event-manage/_components/step-basic/event-name-field.tsx
  apps/admin/app/(main)/event-manage/_components/step-basic/event-type-field.tsx
  apps/admin/app/(main)/event-manage/_components/step-basic/ticket-calendar-field.tsx
  apps/admin/app/(main)/event-manage/_components/step-basic/ticket-count-field.tsx
  apps/admin/app/(main)/event-manage/_components/step-basic/zipcode-field.tsx
  apps/admin/app/(main)/event-manage/_components/step-event/banner-image-field.tsx
  apps/admin/app/(main)/event-manage/_components/step-event/contact-field.tsx
  apps/admin/app/(main)/event-manage/_components/step-event/poster-image-field.tsx
  apps/admin/app/(main)/event-manage/_components/step-event/thumbnail-image-field.tsx
  apps/admin/app/(main)/event-manage/_components/step-payment/bank-code-dialog.tsx
  apps/admin/app/(main)/event-manage/_components/step-payment/payment-code-field.tsx
  apps/admin/app/(main)/event-manage/_components/step-payment/payment-info-field.tsx
  apps/admin/app/(main)/event-manage/_components/step-payment/payment-ticket-price-field.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-account-info.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-basic-info.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-controller.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-event-info.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-payment-info.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-tooltip.tsx
  apps/admin/app/(main)/event-manage/_components/ticket-calendar.tsx
  apps/admin/components/side-nav.tsx
  apps/admin/constants/bank-option.ts
  apps/admin/hooks/use-add-event-form.ts
  apps/admin/package.json
  apps/web/hooks/use-signup-form.ts
  packages/api/src/mutations/use-mutation-submit-event.ts
  packages/api/src/mutations/use-mutation-upload-image.tsx
  packages/api/src/types/admin-auth.ts
  packages/ui/package.json
  packages/ui/src/components/ui/datefield-rac.tsx
  packages/ui/src/components/ui/icon.tsx
  packages/ui/src/prosemirror.css
  packages/util/package.json
  packages/util/src/path.ts
  packages/util/src/time.ts
  pnpm-lock.yaml
Labels: feat, refactor

#46 feat/UKET-134: 회원가입 약관 기능 업데이트
  apps/web/app/(non-auth)/signup/_components/step/step-phone.tsx
  apps/web/app/(non-auth)/signup/_components/step/step-term.tsx
  apps/web/app/(non-auth)/signup/_components/term-section.tsx
  apps/web/hooks/use-term-agreement.ts
  packages/api/src/instance.ts
  packages/api/src/mutations/use-mutation-agree-term.ts
  packages/api/src/queries/term.ts
  packages/api/src/types/term.ts
  packages/ui/src/components/ui/activity.tsx
  packages/util/src/path.ts
Labels: feat, fix

#47 fix/UKET-157: 어드민 행사 등록 관련 QA 반영
  apps/admin/app/(main)/event-manage/_components/step-basic/event-name-field.tsx
  apps/admin/app/(main)/event-manage/_components/step-basic/ticket-calendar-field.tsx
  apps/admin/app/(main)/event-manage/_components/step-basic/zipcode-field.tsx
  apps/admin/app/(main)/event-manage/_components/step-event/contact-field.tsx
  apps/admin/app/(main)/event-manage/_components/step-payment/payment-code-field.tsx
  apps/admin/app/(main)/event-manage/_components/step-payment/payment-info-field.tsx
  apps/admin/app/(main)/event-manage/_components/step-payment/payment-ticket-price-field.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-basic-info.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-payment-info.tsx
  apps/admin/hooks/use-add-event-form.ts
  packages/ui/src/components/ui/icon.tsx
Labels: fix

#49 refactor/UKET-147: 어드민 사용자 추가/삭제 기능 변경 및 버그 수정
  apps/admin/app/(main)/(super-admin)/super-admin/user-manage/_components/admin-form-dialog.tsx
  apps/admin/app/(main)/(super-admin)/super-admin/user-manage/_components/admin-form.tsx
  apps/admin/app/(main)/(super-admin)/super-admin/user-manage/_components/user-add-button.tsx
  apps/admin/app/(main)/(super-admin)/super-admin/user-manage/_components/user-data-table.tsx
  apps/admin/app/(main)/(super-admin)/super-admin/user-manage/_components/user-table-section.tsx
  apps/admin/app/(main)/(super-admin)/super-admin/user-manage/page.tsx
  apps/admin/app/providers.tsx
  apps/admin/hooks/use-new-admin-form.ts
  packages/api/src/mutations/use-mutation-manage-admin.ts
  packages/api/src/queries/admin-user.ts
Labels: fix, refactor

#48 fix/UKET-138: 어드민 에러 픽스
  apps/admin/app/(main)/(super-admin)/super-admin/event-manage/page.tsx
  apps/admin/app/(main)/booking-manage/_components/booking-manage-section.tsx
  apps/admin/components/status-selector.tsx
  apps/admin/hooks/use-next-event-options.ts
  packages/api/src/mutations/use-mutation-change-ticket-status.ts
  packages/api/src/queries/admin-event-info.ts
  packages/api/src/queries/admin-ticket.ts
  packages/api/src/types/admin-event.ts
Labels: fix

#51 Feat/uket 159: admin 메뉴 1:1 채팅, 카카오톡 채널 메뉴 추가
  apps/admin/app/layout.tsx
  apps/admin/components/HelperMenu.tsx
  apps/admin/components/logout-modal.tsx
  apps/admin/components/side-nav.tsx
  packages/api/src/constants/auth-url.ts
Labels: feat

#53 feat/UKET-164: 행사 등록 및 수정 기능 수정
  apps/admin/app/(main)/event-manage/_components/editor/bullet-list-text-area.tsx
  apps/admin/app/(main)/event-manage/_components/editor/editor-menu-bar.tsx
  apps/admin/app/(main)/event-manage/_components/editor/event-editor.tsx
  apps/admin/app/(main)/event-manage/_components/editor/extensions.ts
  apps/admin/app/(main)/event-manage/_components/editor/slash-command.tsx
  apps/admin/app/(main)/event-manage/_components/event-add-section.tsx
  apps/admin/app/(main)/event-manage/_components/step-event/banner-image-field.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-event-info.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-payment-info.tsx
  apps/admin/hooks/use-add-event-form.ts
  apps/admin/hooks/use-textarea.ts
  packages/ui/src/components/ui/icon.tsx
Labels: feat
