Repository DCNJ-Uket/Uket-FE-v2, pull requests merged in 2025-07, with the labels that each got.

#72 style/UKET-220: 행사 등록 가이드 버튼 추가
  apps/admin/app/(main)/event-manage/add/page.tsx
Labels: style

#74 fix/UKET-216: 모바일 로그인 시 FE 수정사항
  apps/admin/components/HelperMenu.tsx
  apps/admin/components/greeting-header.tsx
  apps/admin/components/logout-modal.tsx
Labels: fix

#75 feat/UKET-215: 행사 상태값 별 표시 변경
  apps/admin/app/(main)/(super-admin)/super-admin/event-manage/page.tsx
  apps/web/app/(non-auth)/home/[event]/[id]/_components/uket-event-section.tsx
  apps/web/app/(non-auth)/select-event/_components/uket-event-list.tsx
  packages/api/src/mutations/use-mutation-change-event-status.ts
  packages/api/src/queries/uket-event.ts
  packages/api/src/types/uket-event.ts
  packages/ui/src/components/ui/icon.tsx
Labels: feat, fix, style

#79 style/UKET-245: QA 티켓 처리
  apps/admin/app/(main)/booking-manage/_components/booking-manage-section.tsx
  apps/admin/app/(main)/booking-manage/_components/download-csv.tsx
  apps/admin/app/(main)/entrance-manage/_components/entrance-table-section.tsx
  apps/admin/hooks/use-init-step.ts
  apps/web/app/(auth)/buy-ticket/_components/step/step-complete.tsx
  apps/web/app/(auth)/buy-ticket/_components/step/step-test.tsx
  apps/web/app/(auth)/buy-ticket/_components/step/test-step-complete.tsx
  apps/web/app/(auth)/buy-ticket/test-buy-ticket-section.tsx
  apps/web/app/(auth)/ticket-list/_components/confirm-modal.tsx
  apps/web/app/(auth)/ticket-list/_components/deposit.tsx
  apps/web/app/(auth)/ticket-list/_components/ticket-list-section.tsx
  apps/web/app/(auth)/ticket-list/_components/ticket-modal.tsx
  apps/web/app/(auth)/ticket-list/_components/ticket.tsx
  packages/api/src/queries/reservation.ts
  packages/api/src/queries/user.ts
  packages/api/src/types/admin-ticket.ts
  packages/api/src/types/show.ts
  packages/api/src/types/ticket.ts
  packages/util/src/path.ts
Labels: feat, fix, refactor, style
