Repository DCNJ-Uket/Uket-FE-v2, pull requests merged in 2025-06, with the labels that each got.

#56 fix/UKET-149: 유저/어드민 티켓 상태값 추가(환불요청)
  apps/admin/components/status-selector.tsx
  apps/admin/hooks/use-next-ticket-options.ts
  apps/web/app/(auth)/ticket-list/_components/confirm-modal.tsx
  apps/web/app/(auth)/ticket-list/_components/ticket-modal.tsx
  apps/web/app/(auth)/ticket-list/_components/ticket.tsx
  apps/web/components/indicator.tsx
  packages/api/src/types/admin-ticket.ts
  packages/api/src/types/ticket.ts
  packages/ui/src/components/ui/badge.tsx
Labels: fix

#57 feat/UKET-178: 개발계/운영계 분리 세팅
  apps/web/app/page.tsx
  packages/api/src/admin-instance.ts
  packages/api/src/instance.ts
Labels: feat

#55 Feat/uket 173 : 전화번호 필드 추가, 내행사 관리 prefetch 오류 수정
  apps/admin/app/(main)/(super-admin)/super-admin/event-manage/page.tsx
  apps/admin/app/(main)/(super-admin)/super-admin/user-manage/_components/user-table-section.tsx
  apps/admin/app/(main)/event-manage/_components/event-table-section.tsx
  apps/admin/app/(main)/event-manage/page.tsx
  packages/api/src/queries/admin-event-info.ts
  packages/api/src/types/admin-auth.ts
Labels: feat, fix

#59 style/UKET-186: 유저 서비스 랜딩 페이지 UI 수정
  apps/web/app/page.tsx
  apps/web/components/footer.tsx
Labels: style

#58 style/UKET-182: 유저 티켓 예매 화면 디자인 작업
  apps/web/app/(auth)/buy-ticket/_components/select/counter-button.tsx
  apps/web/app/(auth)/buy-ticket/_components/select/date-select-field.tsx
  apps/web/app/(auth)/buy-ticket/_components/select/datetime-button.tsx
  apps/web/app/(auth)/buy-ticket/_components/select/datetime-select-field.tsx
  apps/web/app/(auth)/buy-ticket/_components/select/performer-select-field.tsx
  apps/web/app/(auth)/buy-ticket/_components/select/performer-sheet.tsx
  apps/web/app/(auth)/buy-ticket/_components/select/ticket-count-field.tsx
  apps/web/app/(auth)/buy-ticket/_components/select/time-select-field.tsx
  apps/web/app/(auth)/buy-ticket/_components/step/step-controller.tsx
  apps/web/app/(auth)/buy-ticket/_components/step/step-select.tsx
  apps/web/app/(auth)/buy-ticket/_components/step/test-step-complete.tsx
  apps/web/app/(auth)/buy-ticket/page.tsx
  apps/web/app/(auth)/buy-ticket/test-buy-ticket-section.tsx
  packages/api/src/types/ticket.ts
  packages/ui/src/components/ui/input.tsx
  packages/util/src/time.ts
Labels: style

#61 style/UKET-187: 로그인(회원가입)/약관 동의 UI 수정
  apps/web/app/(non-auth)/login/page.tsx
  apps/web/app/(non-auth)/signup/_components/step/step-complete.tsx
  apps/web/app/(non-auth)/signup/_components/step/step-term.tsx
  apps/web/app/(non-auth)/signup/_components/term-section.tsx
Labels: style

#63 feat/UKET-191: 슈퍼 관리자 메뉴 접근제한 처리
  apps/admin/components/side-nav.tsx
Labels: feat

#67 fix/UKET-204: 어드민 사용자 추가 오류사항 수정
  apps/admin/app/(main)/(super-admin)/super-admin/user-manage/_components/admin-form-dialog.tsx
  apps/admin/app/(main)/(super-admin)/super-admin/user-manage/_components/user-remove-button.tsx
  apps/admin/hooks/use-new-admin-form.ts
  packages/api/src/error/handler.ts
  packages/api/src/mutations/use-mutation-manage-admin.ts
  packages/ui/src/components/ui/form.tsx
Labels: fix

#66 feat/UKET-169: 어드민 티켓 구매 한도 세팅
  apps/admin/app/(main)/event-manage/_components/step-payment/buy-ticket-limit-field.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-payment-info.tsx
  apps/admin/hooks/use-add-event-form.ts
  packages/api/src/mutations/use-mutation-submit-event.ts
  packages/api/src/queries/admin-event-info.ts
  packages/api/src/types/admin-event.ts
  packages/ui/src/components/ui/icon.tsx
Labels: feat

#70 feat/UKET-184: 입장 그룹 세팅
  apps/admin/app/(main)/event-manage/_components/event-add-section.tsx
  apps/admin/app/(main)/event-manage/_components/step-basic/entry-group-field.tsx
  apps/admin/app/(main)/event-manage/_components/step/step-basic-info.tsx
  apps/admin/hooks/use-add-event-form.ts
  packages/api/src/mutations/use-mutation-submit-event.ts
  packages/api/src/queries/admin-event-info.ts
Labels: feat
